#!/usr/bin/env bash
# Prepare the inputs the design-sync converter needs from packages/web.
#
# packages/web is a Vite application, not a published component library, so it
# ships neither a compiled stylesheet nor a .d.ts tree. This script produces
# both, deterministically, into gitignored locations:
#
#   packages/web/.ds-css/tailwind.css  compiled Tailwind (cfg.cssEntry)
#   packages/web/.ds-types/**          declarations for every component
#   index.d.ts                         types entry the converter reads, mirroring
#                                      the export list in .design-sync/entry.tsx
#
# Run from the repo root. Referenced by cfg.buildCmd — re-run it before any
# re-sync so the converter reads current props and styles.
set -euo pipefail
cd "$(dirname "$0")/.."

echo "→ compiling Tailwind"
(cd packages/web && npx tailwindcss -i src/index.css -o .ds-css/tailwind.css)

echo "→ emitting declarations"
# tsc reports app-level type errors we don't care about here; declarations are
# still written, so don't let a non-zero exit abort the run.
npx tsc -p .design-sync/tsconfig.dts.json || true
test -f packages/web/.ds-types/components/Logo.d.ts \
  || { echo "declaration emit produced nothing — check tsc output above" >&2; exit 1; }

echo "→ generating index.d.ts"
python3 - <<'PY'
import re
src = open('.design-sync/entry.tsx').read()
rx = re.compile(r"^export \{([^}]*)\} from '\.\./packages/web/src/(.*)';$", re.M)
lines = [f"export {{{m.group(1)}}} from './packages/web/.ds-types/{m.group(2)}';"
         for m in rx.finditer(src)]
with open('index.d.ts', 'w') as f:
    f.write("// Generated by .design-sync/prepare.sh — do not edit, do not commit.\n")
    f.write("// Types entry for the design-sync converter; mirrors .design-sync/entry.tsx.\n")
    f.write('\n'.join(lines) + '\n')
PY

echo "✓ prepared ($(grep -c '^export' index.d.ts) export lines)"
