import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { api } from '../api/client';
import { useAuth, useScoreOnly } from '../context/AuthContext';
import { hasFeature, PLAN_LABELS } from '@callguard/shared';
import type { InsightDigest, InsightPriority } from '@callguard/shared';

const PERIOD_OPTIONS = [
  { days: 7, label: '7 days' },
  { days: 30, label: '30 days' },
  { days: 90, label: '90 days' },
];

const PRIORITY_STYLES: Record<InsightPriority, string> = {
  critical: 'bg-fail-bg text-fail border-fail',
  high: 'bg-review-bg text-review border-review',
  medium: 'bg-primary-light text-pass border-pass',
  info: 'bg-table-header text-text-secondary border-border',
};

const PRIORITY_LABELS: Record<InsightPriority, string> = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  info: 'Info',
};

export function AIInsights() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [days, setDays] = useState(7);

  // Insights ships on every plan (see FEATURES.insights in shared) — this
  // only evaluates false for a genuinely invalid/unrecognised plan value, not
  // for any real tier. Route guards above this component guarantee `user` is
  // loaded by the time it renders.
  const hasInsights = hasFeature(user?.organization_plan ?? null, 'insights');

  const { data: digestsData, isLoading } = useQuery({
    queryKey: ['insights'],
    queryFn: () => api.get<{ data: InsightDigest[] }>('/insights'),
    enabled: hasInsights,
  });

  const generate = useMutation({
    mutationFn: () => api.post<InsightDigest>('/insights/generate', { days }),
    onSuccess: (digest) => {
      queryClient.invalidateQueries({ queryKey: ['insights'] });
      setSelectedId(digest.id);
    },
  });

  const digests = digestsData?.data || [];
  const activeDigest = selectedId
    ? digests.find((d) => d.id === selectedId)
    : digests[0];

  if (!hasInsights) {
    return (
      <div>
        <div className="mb-7">
          <h2 className="text-page-title text-text-primary">AI Insights</h2>
          <p className="text-page-sub text-text-subtle mt-1">
            Strategic compliance brief generated by CallGuard AI
          </p>
        </div>
        <div className="bg-card border border-border rounded-card p-10 text-center">
          <svg className="w-10 h-10 mx-auto mb-3 stroke-text-muted" viewBox="0 0 24 24" fill="none" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M12 3l1.9 4.6L18.5 9.5l-4.6 1.9L12 16l-1.9-4.6L5.5 9.5l4.6-1.9L12 3Z" />
            <path d="M19 14l.6 1.6 1.6.6-1.6.6L19 19l-.6-1.6-1.6-.6 1.6-.6L19 14Z" />
          </svg>
          <h3 className="text-lg font-semibold text-text-primary mb-2">
            AI Insights isn't available on your plan
          </h3>
          <p className="text-table-cell text-text-muted max-w-md mx-auto mb-4">
            Get an AI chief-of-staff that turns your call data into a strategic brief every week:
            trends, patterns worth attention, and specific coaching recommendations.
          </p>
          <Link
            to="/settings/organization"
            className="inline-block px-4 py-2 bg-primary hover:bg-primary-hover text-white rounded-btn text-table-cell font-semibold transition-colors"
          >
            Upgrade to {PLAN_LABELS.core}
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-7">
        <div>
          <h2 className="text-page-title text-text-primary">AI Insights</h2>
          <p className="text-page-sub text-text-subtle mt-1">
            Strategic compliance brief generated by CallGuard AI
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex gap-1 bg-card border border-border rounded-btn p-1">
            {PERIOD_OPTIONS.map((opt) => (
              <button
                key={opt.days}
                onClick={() => setDays(opt.days)}
                className={`px-3 py-1.5 rounded-btn text-xs font-semibold transition-colors ${
                  days === opt.days
                    ? 'bg-primary-light text-pass'
                    : 'text-text-muted hover:text-text-primary'
                }`}
              >
                {opt.label}
              </button>
            ))}
          </div>
          <button
            onClick={() => generate.mutate()}
            disabled={generate.isPending}
            className="px-4 py-2 bg-primary hover:bg-primary-hover disabled:opacity-60 disabled:cursor-not-allowed text-white rounded-btn text-table-cell font-semibold transition-colors"
          >
            {generate.isPending ? 'Generating...' : 'Generate new insights'}
          </button>
        </div>
      </div>

      {generate.isError && (
        <div className="bg-fail-bg border-l-[3px] border-l-fail rounded-r-lg p-4 mb-6">
          <div className="text-table-cell font-semibold text-fail">
            Failed to generate insights
          </div>
          <div className="text-xs text-flag-text mt-1">
            {(generate.error as Error).message}
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_280px] gap-4">
        <div>
          {isLoading ? (
            <div className="bg-card border border-border rounded-card p-10 text-center text-text-muted">
              Loading...
            </div>
          ) : !activeDigest ? (
            <div className="bg-card border border-border rounded-card p-10 text-center">
              <svg className="w-10 h-10 mx-auto mb-3 stroke-text-muted" viewBox="0 0 24 24" fill="none" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M4 4v16h16" />
                <path d="M9 17v-5" />
                <path d="M14 17V9" />
                <path d="M19 17v-3" />
              </svg>
              <h3 className="text-base font-semibold text-text-primary mb-2">
                No insights yet
              </h3>
              <p className="text-table-cell text-text-muted max-w-md mx-auto">
                Click "Generate new insights" above to produce your first strategic brief
                based on the last {days} days of calls.
              </p>
            </div>
          ) : (
            <DigestView digest={activeDigest} />
          )}
        </div>

        <div>
          <div className="bg-card border border-border rounded-card overflow-hidden">
            <div className="px-4 py-3 border-b border-border">
              <h3 className="text-table-cell font-semibold text-text-primary uppercase tracking-wider">
                History
              </h3>
            </div>
            {digests.length === 0 ? (
              <div className="px-4 py-6 text-xs text-text-muted text-center">
                No digests yet
              </div>
            ) : (
              <div className="max-h-[600px] overflow-y-auto">
                {digests.map((d) => (
                  <button
                    key={d.id}
                    onClick={() => setSelectedId(d.id)}
                    className={`w-full text-left px-4 py-3 border-b border-border-light last:border-0 hover:bg-table-header transition-colors ${
                      (activeDigest?.id === d.id) ? 'bg-primary-light' : ''
                    }`}
                  >
                    <div className="text-table-cell font-semibold text-text-primary">
                      {formatRange(d.period_start, d.period_end)}
                    </div>
                    <div className="text-[11px] text-text-muted mt-0.5">
                      {formatDate(d.created_at)}
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function DigestView({ digest }: { digest: InsightDigest }) {
  const scoreOnly = useScoreOnly();
  const metrics = digest.metrics as {
    total_calls?: number;
    scored_calls?: number;
    avg_score_current?: number | null;
    pass_rate_current?: number | null;
    corrections_count?: number;
    exemplars_count?: number;
  };

  return (
    <div className="space-y-4">
      {/* Summary card */}
      <div className="bg-card border border-border rounded-card overflow-hidden">
        <div className="px-5 py-4 border-b border-border flex items-center justify-between">
          <div>
            <h3 className="text-section-title text-text-primary">
              {formatRange(digest.period_start, digest.period_end)}
            </h3>
            <div className="text-[11px] text-text-muted mt-0.5">
              Generated {formatDate(digest.created_at)}
            </div>
          </div>
          {digest.model_id && (
            <span className="text-[10px] uppercase tracking-wider text-text-muted bg-table-header px-2 py-1 rounded">
              CallGuard AI
            </span>
          )}
        </div>

        {/* Metrics strip — Pass rate is verdict-derived, hidden in score-only mode. */}
        <div className={`grid grid-cols-2 ${scoreOnly ? 'sm:grid-cols-3' : 'sm:grid-cols-4'} border-b border-border-light`}>
          <MetricCell label="Calls" value={metrics.total_calls ?? '—'} />
          <MetricCell
            label="Avg score"
            value={metrics.avg_score_current != null ? `${metrics.avg_score_current.toFixed(1)}%` : '—'}
          />
          {!scoreOnly && (
            <MetricCell
              label="Pass rate"
              value={metrics.pass_rate_current != null ? `${metrics.pass_rate_current.toFixed(1)}%` : '—'}
            />
          )}
          <MetricCell
            label="Corrections"
            value={metrics.corrections_count ?? 0}
          />
        </div>

        <div className="px-5 py-4">
          <div className="text-table-cell text-text-cell leading-relaxed whitespace-pre-wrap">
            {digest.summary}
          </div>
        </div>
      </div>

      {/* Recommendations */}
      <div className="bg-card border border-border rounded-card overflow-hidden">
        <div className="px-5 py-4 border-b border-border">
          <h3 className="text-section-title text-text-primary">
            Recommendations
          </h3>
        </div>
        <div>
          {digest.recommendations.map((rec, idx) => (
            <div
              key={idx}
              className="px-5 py-4 border-b border-border-light last:border-0"
            >
              <div className="flex items-start gap-3">
                <span
                  className={`flex-shrink-0 px-2 py-[3px] rounded text-[10px] font-bold uppercase tracking-wider border ${
                    PRIORITY_STYLES[rec.priority] || PRIORITY_STYLES.info
                  }`}
                >
                  {PRIORITY_LABELS[rec.priority] || rec.priority}
                </span>
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-semibold text-text-primary">
                    {rec.title}
                  </div>
                  <div className="text-table-cell text-text-cell mt-1 leading-relaxed">
                    {rec.detail}
                  </div>
                  {rec.cta && (
                    <Link
                      to={rec.cta.href}
                      className="inline-block mt-2 text-xs text-primary hover:text-primary-hover font-semibold"
                    >
                      {rec.cta.label} →
                    </Link>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function MetricCell({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="px-5 py-3 border-r border-border-light last:border-0">
      <div className="text-[10px] uppercase tracking-wider text-text-muted font-semibold">
        {label}
      </div>
      <div className="text-lg font-bold text-text-primary font-mono mt-0.5">
        {value}
      </div>
    </div>
  );
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatRange(startIso: string, endIso: string): string {
  const start = new Date(startIso);
  const end = new Date(endIso);
  const fmt: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short' };
  return `${start.toLocaleDateString('en-GB', fmt)} – ${end.toLocaleDateString('en-GB', fmt)}`;
}
